### ISSUE TITLE
What the values in npy files in Frustration-Energy-space folder stand for?

### ISSUE THREAD

**Issue by 2865175617** [Gxy-with-luv/AFF2024#3]
Hi,

Thanks for your amazing work, it could be really helpful for my current project!

I am having trouble understanding what the values in both of your .npy files stand for. They look like an array containing energy information for each residue to me, but I do not understand what exactly they are.

**Comment by shuren7** [comment]
Is the author still online?  I am also not quite clear about how the files "AFF2024/AdK/Frustration-Energy-space/ENE_sing.npy" and "AFF2024/AdK/Frustration-Energy-space/ENE_nat.npy" were generated.  It seems that they were produced through Rosetta.  However, the specific process of obtaining them remains somewhat unclear.

**Comment by Gxy-with-luv** [comment]
Thank you all for your interest in this project! I sincerely apologize for the delayed response.

Last year, I was visiting Kyoto University, and unfortunately, my Nanjing University academic email had some unusual blocking and spam filtering mechanisms. While I was outside of China, I was primarily using my Gmail (xingyuenju@gmail.com), but my GitHub account is linked to my Nanjing University email. As a result, I only received the new notifications today and just realized that I had missed these messages. I am truly sorry for this oversight.

Regarding the .npy files: These contain energy information for both the original system (query sequence + original structure) and the threaded system. The provided Rosetta script can calculate detailed energy values for both the original and threaded systems (i.e., pairwise residue-residue energy terms E_{ij}). As described in the supplementary materials of our paper, we use single-residue energy values (E_i = \sum_j E_{ij}), and these .npy files contain exactly those single-residue energy values.

Again, I sincerely apologize for the delay.

**Comment by shuren7** [comment]
Hello @Gxy-with-luv , thank you very much for your response! If we had guidance from the creators, our work would be significantly easier.

This software is intriguing, and we are also interested in utilizing it for our own research. However, I hope you can understand that I am not a computer science or biophysics major, but rather a genetics major. As such, I may not be very familiar with many specialized concepts and code-related aspects. My environment is still being configured, and I primarily hope to consult on several issues.

Generally speaking, I can roughly understand the principles, although I am not an expert in this field. However, the main point of confusion lies in the program's execution process.

1) The most significant issue still revolves around the operation of Rosetta. In the guide, the "Rosetta_scripts/" file seems to have been deleted for some reason, which has puzzled me for a long time. Although I later stumbled upon the previous "Rosetta_scripts/" file by chance, it appears that Rosetta is executed via the following script （template.sh）: 

```
#BSUB -q 7702ib 
#BSUB -J pro
#BSUB -n 24
#BSUB -o outwater
#BSUB -e errwater
#export OMP_NUM_THREADS=1
#source /fs00/software/lsf/misc/ompthreads.sh

module load gcc/8.3.0
module load fftw/3.3.7-iccifort-17.0.6-avx2
module load zlib/1.2.11
module load impi/5.0.3.048

export PLUMED_KERNEL=/fsa/home/ww_guanxy/enableplumed/plumed/lib/libplumedKernel.so
source /fsa/home/ww_guanxy/enableplumed/gromacs/bin/GMXRC.bash
source /fsa/home/ww_guanxy/amber20/amber.sh
export LD_LIBRARY_PATH=/fsa/home/ww_guanxy/enableplumed/plumed/lib:$LD_LIBRARY_PATH

...
```

I noticed that "template.sh" seems to involve numerous sequences. My question is whether these sequences are generated by the "RandSeq.py" script in the "AtomicFrustratometer_Results-master" mentioned in "the first issue" (https://github.com/Gxy-with-luv/AFF2024/issues/1). Additionally, is the general process similar to the one executed in "job.sh"? Is it through this general process that the "ENE_sing.npy" and "ENE_nat.npy" files in "Walkthrough.ipynb" are obtained?


2）Regarding the Frustratometer web server, I obtained the "2025327418543534_configurational_5adens" file for the sequence of interest. However, I am curious about the origin of the .npy files, which seem to come from the "getmsaene_nat.py" and "getmsaene_sing.py" scripts. It appears that the code in "getmsaene_sing.py" requires a 'tertiary_frustration.dat' file, which must be obtained through the Frustratometer. If the web version cannot generate this file, is it necessary to use the R version (https://github.com/proteinphysiologylab/frustratometeR) to create it?

3）The overall confusing aspect remains in the section illustrated in the figure below, where the origins of certain files appear unclear. While I can successfully compute the case you provided on the server, I find myself puzzled regarding the sources of my own sequence. The situation is like this. I appreciate your understanding, as I am a novice in coding, and there are many concepts that may seem obvious but are not clear to me.

![Image](https://github.com/user-attachments/assets/3c35ae4b-91f7-4f49-b8d5-2c18f9c2c83e)

Thanks！

**Comment by shuren7** [comment]
I apologize for any mistakes in my previous response @Gxy-with-luv . I have reviewed the content of your 'Supporting Information Text.' The main issue now is: What specific commands of Rosetta should I use to thread each of the MSA sequences onto the reference structure and calculate detailed energy values for both the original and threaded systems? 

I must admit that I am not specialized in computer science or biophysics, so this task poses quite a challenge for me. I appreciate your understanding.

**Comment by shuren7** [comment]
Dear @Gxy-with-luv @wtren 
After overcoming numerous challenges, I have gained a preliminary understanding of the software's operational process. However, I am still encountering an issue: when I execute the "getmsaene_sing.py" script in an attempt to generate a ".npy" file (using ADK as an example), the following error occurs. How can I resolve this?

“Traceback (most recent call last):
  File "/home/w/new-cap/open-pri/AFF2024-1/rosetta/AFF2024-e59464f9f0e7f04fdf1bfde93c5a27bf21bf4031/Rosetta_scripts/Rosetta_AdK/getmsaene_sing.py", line 47, in <module>
    eneres[aa2] += 0.5 * ene
IndexError: index 512 is out of bounds for axis 0 with size 214
”

**Comment by Gxy-with-luv** [comment]
Thank you for your thoughtful response, @shuren7 . No worries about any mistakes! ;)

To thread each MSA sequence onto the reference structure and calculate detailed energy values in Rosetta, you can check the following scripts for reference:

1. Rosetta input (in `.xml` format) for threading new sequence and then calculating the energy:
```
<ROSETTASCRIPTS>
        <SCOREFXNS>
        </SCOREFXNS>
	<RESIDUE_SELECTORS>
		<Neighborhood name="nbrhood" resnums="1A-214A"/>
		<Not name="others" selector="nbrhood" />
	</RESIDUE_SELECTORS>
	<TASKOPERATIONS>
		<OperateOnResidueSubset name="turn_off_others" selector="others">
			<PreventRepackingRLT/> 
		</OperateOnResidueSubset>
		<RestrictToRepacking name="rtrp"/>
	</TASKOPERATIONS>
        <FILTERS>
		<ScoreCutoffFilter name="scofilter" report_residue_pair_energies="1" cutoff="50000000.0" />
        </FILTERS>
	<SIMPLE_METRICS>
	</SIMPLE_METRICS>
	
        <MOVERS>
		<SimpleThreadingMover name="threader" start_position="1A" thread_sequence="GKRSNTTGK" pack_neighbors="1" neighbor_dis="10"  pack_rounds="10" />
		<FastRelax name="fast_relax" task_operations="rtrp,turn_off_others" relaxscript="rosettacon2018" repeats="6">
			<MoveMap name="backbone">
				<Span begin="1" end="214" chi="1" bb="0"/>
			</MoveMap>
		</FastRelax>
        </MOVERS>
        <APPLY_TO_POSE>
        </APPLY_TO_POSE>
        <PROTOCOLS>
		<Add mover="threader" /> #Add this line
		<Add mover_name="fast_relax"/>
		<Add filter="scofilter" />
        </PROTOCOLS>
</ROSETTASCRIPTS>
```
where the "thread_sequence" should be replaced by a new sequence, like in our case the sequences from AdK MSA space.

2. Run this input by Rosetta (bash), in our case for every sequence from the MSA space:
```let "j=0"
while read line; do
	let "j=j+1"
	sed -i "s/GKRSNTTGK/$line/" ./jobdir${idx}/test.xml
	$path2rosetta/main/source/bin/rosetta_scripts.linuxgccrelease -parser:protocol  ./jobdir${idx}/test.xml -s ./jobdir${idx}/3gso.pdb -out:path:pdb ./jobdir${idx} -overwrite -ignore_zero_occupancy false > ./jobdir${idx}/$j.log
	cat ./jobdir${idx}/$j.log | grep "ResResE" > ./jobdir${idx}/temp
	mv ./jobdir${idx}/temp  ./jobdir${idx}/$j.log
	mv ./jobdir${idx}/3gso_0001.pdb ./jobdir${idx}/$j.pdb
	sed -i "s/$line/GKRSNTTGK/" ./jobdir${idx}/test.xml
done < jobdir${idx}/pep${idx}.txt
```


Let me know if you have any questions—I’d be happy to help! 😊

**Comment by Gxy-with-luv** [comment]
`Dear @Gxy-with-luv @wtren
After overcoming numerous challenges, I have gained a preliminary understanding of the software's operational process. However, I am still encountering an issue: when I execute the "getmsaene_sing.py" script in an attempt to generate a ".npy" file (using ADK as an example), the following error occurs. How can I resolve this?

“Traceback (most recent call last):
File "/home/w/new-cap/open-pri/AFF2024-1/rosetta/AFF2024-e59464f9f0e7f04fdf1bfde93c5a27bf21bf4031/Rosetta_scripts/Rosetta_AdK/getmsaene_sing.py", line 47, in
eneres[aa2] += 0.5 * ene
IndexError: index 512 is out of bounds for axis 0 with size 214
”`

214 is the sequence length of AdK, thus should be replaced by the actual sequence length of the protein you are dealing with ;)

**Comment by shuren7** [comment]
Thank you for the guidance, Xingyue @Gxy-with-luv. I will try my own sequence later to see if it works~.

wen

**Comment by shuren7** [comment]
> 214 is the sequence length of AdK, thus should be replaced by the actual sequence length of the protein you are dealing with ;)


I tried but there are still errors, I don't know why?

1）python getmsaene_nat.py
```
Traceback (most recent call last):
  File "/home/w/new-cap/open-pri/AFF2024-1/rosetta/AFF2024-e59464f9f0e7f04fdf1bfde93c5a27bf21bf4031/Rosetta_scripts/Rosetta_CAP/getmsaene_nat.py", line 28, in <module>
    eneres[aa2] += 0.5 * ene
IndexError: index 5331 is out of bounds for axis 0 with size 1020
```

getmsaene_nat.py:
```
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 22 15:01:04 2023

@author: Administrator
"""
import numpy as np

pairs = []
for i in range(0, 1020):
    for j in range(i, 1020):
        pairs.append([i, j])
box = []
enes = []
singres = []
enelog = []
logfile = 'native.log'
eneres = np.zeros([1020])
with open(logfile, 'r') as fi:
    for line in fi:
        line = line.split()
        if 'Res1' not in line and 'nonzero' not in line and float(line[4]) <= 5.000:
            aa1 = int(float(line[1].split('_')[1][1:])) - 1
            aa2 = int(float(line[2].split('_')[1][1:])) - 1
            ene = float(line[-1]) - 1.0*(float(line[4])) - \
                float(line[10]) - float(line[15])
            eneres[aa1] += 0.5 * ene
            eneres[aa2] += 0.5 * ene
for pair in pairs:
    enelog.append(eneres[pair[0]] + eneres[pair[1]])
enes.append(enelog)
singres.append(eneres)
enes = np.array(enes)
meanene = np.mean(enes, axis=0)
stdene = np.std(enes, axis=0)
singres = np.array(singres)
meansing = np.mean(singres, axis=0)
stdsing = np.std(singres, axis=0)
box.append(singres)
np.save('natbox.npy', box)

```

python getmsaene_sing.py 

```
0
Traceback (most recent call last):
  File "/home/w/new-cap/open-pri/AFF2024-1/rosetta/AFF2024-e59464f9f0e7f04fdf1bfde93c5a27bf21bf4031/Rosetta_scripts/Rosetta_CAP/getmsaene_sing.py", line 47, in <module>
    eneres[aa2] += 0.5 * ene
IndexError: index 5331 is out of bounds for axis 0 with size 1020

```

getmsaene_sing.py:
```
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 10 16:54:50 2023

@author: Administrator
"""
import numpy as np
import glob

natfile = 'tertiary_frustration.dat'

pairs = []
for i in range(0, 1020):
    for j in range(i, 1020):
        pairs.append([i, j])

box = []
box2 = []


lst = np.arange(0,30)
for dirnm in lst:
    print(dirnm)
    dirname = './jobdir'+str(dirnm)+'/'
    files = glob.glob(dirname + '*.pdb')
    # print(files)
    N = len(files) - 2
    enes = []
    singres = []
    for idx in range(1, N+1):
        enelog = []
        logfile = dirname+'/'+str(idx)+'.log'
        # print(logfile)
        # logfile = dirname+'/native.log'
        eneres = np.zeros([1020])
        with open(logfile, 'r') as fi:
            for line in fi:
                line = line.split()
                if 'file' in line:
                    continue
                if 'Res1' not in line and 'nonzero' not in line and float(line[4]) <= 5.000:
                    aa1 = int(float(line[1].split('_')[1][1:])) - 1
                    aa2 = int(float(line[2].split('_')[1][1:])) - 1
                    ene = float(line[-1]) - 1.0*(float(line[4])) - \
                        float(line[10]) - float(line[15])
                    eneres[aa1] += 0.5 * ene
                    eneres[aa2] += 0.5 * ene
        for pair in pairs:
            enelog.append(eneres[pair[0]] + eneres[pair[1]])
        enes.append(enelog)
        singres.append(eneres)

    enes = np.array(enes)
    meanene = np.mean(enes, axis=0)
    stdene = np.std(enes, axis=0)

    singres = np.array(singres)
    meansing = np.mean(singres, axis=0)
    stdsing = np.std(singres, axis=0)
    box.append(singres)
    # box2.append(stdsing)

box = np.array(box)
np.save('boxsing.npy', box)
```

"1020" is the length of my sequence.

[MSA.a3m.txt](https://github.com/user-attachments/files/19548553/MSA.a3m.txt)

[native.seq.txt](https://github.com/user-attachments/files/19548558/native.seq.txt)

Could you take a look?  Thank you!
Wen

**Comment by shuren7** [comment]
I found that the problem seems to be with the version of Rosetta.  The amino acid numbering in the "log" file generated by the Rosetta installed via conda does not appear to be in the conventional format.  Attempting to resolve it...

**Comment by dadadaqingtian** [comment]
Hello, have you resolved the issue? I’m experiencing the same 

> I found that the problem seems to be with the version of Rosetta. The amino acid numbering in the "log" file generated by the Rosetta installed via conda does not appear to be in the conventional format. Attempting to resolve it...

**Comment by shuren7** [comment]
Hello, thank you for your reply. I found that we need to use a script to replace numbers with corresponding letters.
---- Replied Message ----
| From | ***@***.***> |
| Date | 5/14/2025 21:13 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [Gxy-with-luv/AFF2024] What the values in npy files in Frustration-Energy-space folder stand for? (Issue #3) |
dadadaqingtian left a comment (Gxy-with-luv/AFF2024#3)

Hello, have you resolved the issue? I’m experiencing the same

I found that the problem seems to be with the version of Rosetta. The amino acid numbering in the "log" file generated by the Rosetta installed via conda does not appear to be in the conventional format. Attempting to resolve it...
